name: store_builder
description: Flux store and builder for Flutter
author: najeira <najeira@gmail.com>
version: 0.2.1
homepage: https://github.com/najeira/flutter-store-builder

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.1 <2.0.0"
